service: motorbike-shop
frameworkVersion: '3'

package:
  individually: true
  patterns:
    - "!*/**"

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'
  serverless-dynamodb:
    stages:
      - dev
    start:
      inMemory: true
      migrate: true
      docker: true

provider:
  name: aws
  region: us-east-2
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: arn:aws:dynamodb:${AWS:region}:${AWS:AccountId}:table/customersTable

functions:
  create-customer:
    handler: src/motorbike-shop/infraestructure/controllers/create.handler
    package: 
      patterns:
        - '!src/test/**'
        - 'src/motorbike-shop/infraestructure/controllers/create.ts'
        - 'src/motorbike-shop/application/create.application.ts'
        - 'src/motorbike-shop/domain/customer.dto.ts'
        - 'src/motorbike-shop/domain/customer.repository.ts'
        - 'src/motorbike-shop/infraestructure/guards/body-request.guard.ts'
        - 'src/motorbike-shop/infraestructure/aws/dynamodb.client.ts'
        - 'src/motorbike-shop/infraestructure/db/dynamodb.repository.ts'
    events:
      - http:
          path: customers
          method: POST
          request:
            schemas:
              application/json: ${file(src/motorbike-shop/domain/schemas/customer.schema.json)}

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb
  - serverless-offline

resources:
  Resources:
    customersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: credit
            AttributeType: N
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: credit
            KeySchema:
              - AttributeName: pk
                KeyType: HASH
              - AttributeName: credit
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1