PATCH http://localhost:3000/dev/customers/27cf0a0f-a745-410a-8593-d24eaf9282a2
Content-Type: application/json

{
  "name": "Juan Escamilla",
  "email": "jmke.mat@gmail.com",
  "phone": "9842773217",
  "address": "Calle"
}